[cargo-vet]
version = "0.10"

[imports.google]
url = "https://raw.githubusercontent.com/google/rust-crate-audits/main/audits.toml"

[policy.fe_reader_core]
criteria = ["safe-to-run", "safe-to-deploy"]

[policy.fe_reader_pdf_model]
criteria = ["safe-to-run", "safe-to-deploy"]
